version: '{build}'

image: Visual Studio 2017

build_script:
- cmd: >-
    set sln=Autodesk/Revit/src/RhinoInside.Revit.sln

    msbuild %sln% /t:restore;build /p:Configuration="Release 2017"
    msbuild %sln% /t:restore;build /p:Configuration="Release 2018"
    msbuild %sln% /t:restore;build /p:Configuration="Release 2019"

    msbuild Autodesk/Revit/src/RhinoInside.Revit.Setup.sln /p:Configuration=Release

artifacts:
- path: Autodesk\Revit\src\RhinoInside.Revit.Setup\bin\x64\Release\RhinoInside.Revit.msi
